### ISSUE TITLE
GPL 2.0 licensed dependency 

### ISSUE THREAD

**Issue by donbobka** [mountain-pass/addressr#356]
Addresser uses `cfonts` package that are licensed under GPL 2.0 that makes it incompatible with addressr's Apache-2.0 license.

**Comment by tompahoward** [comment]
Thanks for the heads up. I’ll check this and fix ASAP

**Comment by tompahoward** [comment]
@dominikwilkowski, we inadvertently included you cfonts library this Apache-2.0 licensed program. We have removed, but I wanted to reach to let you know and to find out if there is anything else you wanted us to do.

**Comment by dominikwilkowski** [comment]
Hey @tompahoward 

Appreciate the diligence and care here. No need to do anything else.
