### ISSUE TITLE
Loader fails on NOV 21 Data

### ISSUE THREAD

**Issue by tompahoward** [mountain-pass/addressr#361]

**Comment by gelsas** [comment]
![unnamed](https://user-images.githubusercontent.com/282734/145153031-dabb66ce-536a-4d29-b7ec-3dbefacc4295.png)

Getting this error with addressr version 1.0.262

These are the steps which led to this error:

- Installed centos7.
- Configured nginx.
- Installed docker using these commands:
• sudo yum install -y yum-utils
• sudo yum-config-manager \ --add-repo \ https://download.docker.com/linux/centos/docker-ce.repo

docker engine:
- sudo yum install docker-ce docker-ce-cli containerd.io

start docker:
- sudo systemctl start docker

installed npm using these commands:
- curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
- sudo yum install nodejs
- node –version

Install addressr
- sudo npm install @mountainpass/addressr -g
- sudo docker pull docker.elastic.co/elasticsearch/elasticsearch:7.2.0
- docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node"
docker.elastic.co/elasticsearch/elasticsearch:7.2.

Start API server. In a second window run:
- export ELASTIC_PORT=9200
- export ELASTIC_HOST=localhost
- addressr-server

Setup the env vars for the data loader. In a third window run:
- export ELASTIC_PORT=9200
- export ELASTIC_HOST=localhost
- export ADDRESSR_INDEX_TIMEOUT=30s
- export ADDRESSR_INDEX_BACKOFF=1000
- export ADDRESSR_INDEX_BACKOFF_INCREMENT=1000
- export ADDRESSR_INDEX_BACKOFF_MAX=10000

Run data Loader
- addressr-loader

Causes then the error which can be seen in the screenshot.
