### ISSUE TITLE
Support both Elasticsearch and OpenSearch

### ISSUE THREAD

**Issue by koresar** [mountain-pass/addressr#363]
Hey, would you accept a PR which adds support for both Elasticsearch and OpenSearch?

The fix is simple - pin the `@elastic/elasticsearch` to this exact version `7.13.0`.

**Comment by tompahoward** [comment]
We've updated to OpenSearch https://github.com/mountain-pass/addressr/commit/362270bdb6fbcbfadc520df276b05027d7930b65

And to answer your question, yes, we would have. 👍

**Comment by koresar** [comment]
Wow. Thanks for the update!
