### ISSUE TITLE
The quick start guide is incomplete..

### ISSUE THREAD

**Issue by mattjis** [mountain-pass/addressr#5]
I can't figure out how to get a server running with Adressr because the quick start guide is missing key information.

**What I tried:**

1. Created a "droplet" server on [DigitalOcean](https://www.digitalocean.com) Ubuntu 20.04 (LTS) x64 w/ 2gb of Ram and 50gb SSD storage.
2. Installed NPM & Docker
3. Attempted to run each command from the terminal according to the quick start guide.

**Result:**

Immediately I was running into issues. 

Some of the commands run the service inside terminal, which when I close terminal the service does too.

What am I doing wrong? How do I get this thing going?

Any help would be greatly appreciated.
Thanks!

**Comment by mattjis** [comment]
@tompahoward

**Comment by koresar** [comment]
@mattjis Before doing the item 3 you would need to open another terminal window or tab. E.g. ssh to that virtual machine (droplet) one more time.

I'm doing all that on my machine (Mac OS). Works fine!
@tompahoward you are a genius.

**Comment by tompahoward** [comment]
@mattjis , sorry I missed this before now. Glad you got it working. Let me know if you need any more help 👍

**Comment by tompahoward** [comment]
@koresar  thanks 😊

**Comment by mattjis** [comment]
@koresar are we meant to leave these terminal windows open 24/7 to use the addressr server?

**Comment by mattjis** [comment]
@tompahoward I never ended up getting it working. Installing elastic search would never finish, it would just hang in the terminal window, with the last like saying something about a key

**Comment by tompahoward** [comment]
@mattjis  you can use `[nohup](https://www.maketecheasier.com/nohup-and-uses/#:~:text=Nohup%20is%20a%20supplemental%20command,sh%20your%2Dscript.sh%20%26)` to prevent the process from exiting when you close the terminal window. 

> Installing elastic search would never finish
Are you talking about this step
`docker pull docker.elastic.co/elasticsearch/elasticsearch:7.2.0
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.2.0`
or this step
`addressr-loader`

**Comment by koresar** [comment]
@mattjis I see you have a number of things to learn before doing production-ready DevOps. It seems impossible to educate you with al the necessary DevOps basics in GitHub issue comments.
I'd recommend hiring/consulting with someone experienced.

**Comment by mattjis** [comment]
@tompahoward Ah okay I see. Would I have to do this nohup every time I restart the server? Is there a way to get everything to start by itself on server restart?

**Comment by mattjis** [comment]
@tompahoward Both of those steps

**Comment by tompahoward** [comment]
@mattjis I normally use [Terraform](https://www.terraform.io/) to get everything up and running.  The quick start is literally that, just a guide to get started so you can figure out if it does what you need.

Production deployments (for this and most other things) requires much much much more work. Our Terraform scripts for deploying addresser weigh in at over 200 LoC.

**Comment by koresar** [comment]
@mattjis you should hire @tompahoward :)

**Comment by tompahoward** [comment]
@mattjis In the meantime, I've updated the quick start to make the use of separate windows explicit. 👍

**Comment by mattjis** [comment]
@tompahoward thanks so much! I really appreciate it
